#!/usr/bin/env ruby

require 'date'

o = ARGV[0].chomp
d = ARGV[1].chomp
case o
when '-ms'
  d = DateTime.strptime(d, '%Q')
when '-s'
  d = DateTime.strptime(d, '%s')
when '-di'
  d = DateTime.strptime(d, '%Y%m%d')
end
puts "#{d.strftime('%Y-%m-%d : %H:%M:%S : %z')}"
puts "ms: #{d.strftime('%Q')}"
puts "s: #{d.strftime('%s')}"

